#!/bin/sh

## ---------------------------------------------------
## Basic Define
## ---------------------------------------------------
SCRIPT_NAME=$(basename $0)
SCRIPT_BASEDIR="$( cd "$( dirname "$0" )" && pwd )"

## function
function gen_log_names(){
  log_path=$1
  arr=( `ls $log_path | grep -P '(.*)\.[0-9]+$' | sort ` )
  for (( i = 0; i < ${#arr[@]} - 1; i++ ));
  do
    log_names="$log_names $log_path/${arr[$i]}"
  done
}

## generate file string
log_names=""


## ---------------------------------------------------
## unmap caches
## ---------------------------------------------------

## binlog path - Change me
gen_log_names /log/binary-log
gen_log_names /log/relay-log

## unmap cache
echo "-----------------------------------------------------------------------"
echo "`date` cache unmap.. start"
echo "-----------------------------------------------------------------------"
free | grep Mem
echo "-----------------------------------------------------------------------"
$SCRIPT_BASEDIR/lib/unmap_cache  $log_names
echo "-----------------------------------------------------------------------"
free | grep Mem
